name: prettier

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '21 3 * * 4'

jobs:
  run-prettier:
    name: Run prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: 'pnpm'

      - name: Install Node.js dependencies
        run: |
          pnpm install
          pnpm dlx prisma generate

      - name: Run prettier
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          prettier: true 